# Generated by Django 2.2.24 on 2023-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('election', 'Eleição'), ('referendum', 'Referendo')], default='election', max_length=250),
        ),
    ]
